hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "allium/hexverb-client/Patterns/placeholder.lua"

[[files]]
file = "allium/hexverb-client/Registry/hexverbPatternRegistry.lua"

[[files]]
file = "allium/hexverb-client/main.lua"

[[files]]
file = "allium/hexverb-client/manifest.json"

[[files]]
file = "config/CoroUtil/General.toml"

[[files]]
file = "config/DistantHorizons.toml"

[[files]]
file = "config/MouseTweaks.cfg"

[[files]]
file = "config/NoChatReports/NCR-Client.json"

[[files]]
file = "config/NoChatReports/NCR-Common.json"

[[files]]
file = "config/NoChatReports/NCR-Encryption.json"

[[files]]
file = "config/NoChatReports/NCR-ServerPreferences.json"

[[files]]
file = "config/amendments-client.json"

[[files]]
file = "config/amendments-common.json"

[[files]]
file = "config/appleskin.json5"

[[files]]
file = "config/armourers_workshop-client.toml"

[[files]]
file = "config/armourers_workshop-common.toml"

[[files]]
file = "config/authme.json5"

[[files]]
file = "config/betteradvancements.json"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/cardinal-components-api.properties"

[[files]]
file = "config/carpet/default_carpet-fixes.conf"

[[files]]
file = "config/carpet/default_carpet.conf"

[[files]]
file = "config/carryon-client.json"

[[files]]
file = "config/carryon-common.json"

[[files]]
file = "config/chunky/config.json"

[[files]]
file = "config/chunkyborder/borders.json"

[[files]]
file = "config/chunkyborder/config.json"

[[files]]
file = "config/complexhex/client.json5"

[[files]]
file = "config/complexhex/common.json5"

[[files]]
file = "config/complexhex/server.json5"

[[files]]
file = "config/computercraft-client.toml"

[[files]]
file = "config/configChanges/moderate-loading-screen.json5"

[[files]]
file = "config/configChanges/styled-chat.json"

[[files]]
file = "config/configChanges/styled-nicknames.json"

[[files]]
file = "config/create-client.toml"

[[files]]
file = "config/create-common.toml"

[[files]]
file = "config/create-server.toml"

[[files]]
file = "config/create-tweaks-common.toml"

[[files]]
file = "config/cristellib/minecraftED.json5"

[[files]]
file = "config/cristellib/minecraftP.json5"

[[files]]
file = "config/deathlog.json5"

[[files]]
file = "config/default-hotkeys.json"

[[files]]
file = "config/dummmmmmy-client.json"

[[files]]
file = "config/dummmmmmy-common.json"

[[files]]
file = "config/effective.json"

[[files]]
file = "config/emi.css"

[[files]]
file = "config/ephemera/client.json5"

[[files]]
file = "config/ephemera/common.json5"

[[files]]
file = "config/ephemera/server.json5"

[[files]]
file = "config/expanded_ecosphere/config.json5"

[[files]]
file = "config/expanded_ecosphere/replace_biomes.json5"

[[files]]
file = "config/extremesoundmuffler.json5"

[[files]]
file = "config/fabric/indigo-renderer.properties"

[[files]]
file = "config/fabric_loader_dependencies.json"

[[files]]
file = "config/fabrication/block_logo.ini"

[[files]]
file = "config/fabrication/block_logo.png"

[[files]]
file = "config/fabrication/classic_block_drops.ini"

[[files]]
file = "config/fabrication/dimensional_tools.ini"

[[files]]
file = "config/fabrication/features.ini"

[[files]]
file = "config/fabrication/fscript.ini"

[[files]]
file = "config/fabrication/gear_components.ini"

[[files]]
file = "config/fabrication/item_despawn.ini"

[[files]]
file = "config/fabrication/taggable_players.ini"

[[files]]
file = "config/fabrication/yeet_recipes.ini"

[[files]]
file = "config/farmersdelight-client.toml"

[[files]]
file = "config/farmersdelight-common.toml"

[[files]]
file = "config/figura.json"

[[files]]
file = "config/flywheel.json"

[[files]]
file = "config/forgeconfigapiport.toml"

[[files]]
file = "config/fzzy_config/keybinds.toml"

[[files]]
file = "config/gravity_changer.json"

[[files]]
file = "config/helpfromhexxy/client.json5"

[[files]]
file = "config/helpfromhexxy/common.json5"

[[files]]
file = "config/helpfromhexxy/server.json5"

[[files]]
file = "config/hexal/client.json5"

[[files]]
file = "config/hexal/common.json5"

[[files]]
file = "config/hexal/server.json5"

[[files]]
file = "config/hexcassettes.json"

[[files]]
file = "config/hexcasting/client.json"

[[files]]
file = "config/hexcasting/common.json"

[[files]]
file = "config/hexcasting/server.json"

[[files]]
file = "config/hexdebug/client.toml"

[[files]]
file = "config/hexdebug/server.toml"

[[files]]
file = "config/hexportation/client.json5"

[[files]]
file = "config/hexportation/common.json5"

[[files]]
file = "config/hexportation/server.json5"

[[files]]
file = "config/hexstruction/client.toml"

[[files]]
file = "config/hexstruction/server.toml"

[[files]]
file = "config/hexxyinthealps/client.toml"

[[files]]
file = "config/hexxyinthealps/server.toml"

[[files]]
file = "config/hierophantics.json5"

[[files]]
file = "config/hierophantics/client.toml"

[[files]]
file = "config/hierophantics/server.toml"

[[files]]
file = "config/immersive_paintings.json"

[[files]]
file = "config/indium-renderer.properties"

[[files]]
file = "config/inline/client-config.toml"

[[files]]
file = "config/iris.properties"

[[files]]
file = "config/item_obliterator.json5"

[[files]]
file = "config/jade/hide-blocks.json"

[[files]]
file = "config/jade/hide-entities.json"

[[files]]
file = "config/jade/jade.json"

[[files]]
file = "config/jade/plugins.json"

[[files]]
file = "config/jade/server-plugin-overrides.json"

[[files]]
file = "config/jade/sort-order.json"

[[files]]
file = "config/jline4mcdsrv.toml"

[[files]]
file = "config/jsonpatcher.json"

[[files]]
file = "config/justzoom/config.txt"

[[files]]
file = "config/konkrete/locals/de_de.local"

[[files]]
file = "config/konkrete/locals/en_us.local"

[[files]]
file = "config/konkrete/locals/pl_pl.local"

[[files]]
file = "config/konkrete/locals/pt_br.local"

[[files]]
file = "config/leavesbegone-server.toml"

[[files]]
file = "config/ledger.toml"

[[files]]
file = "config/libgui.json5"

[[files]]
file = "config/lithium.properties"

[[files]]
file = "config/lmft.json"

[[files]]
file = "config/lodestone-client.toml"

[[files]]
file = "config/lootr.json"

[[files]]
file = "config/midnightlib.json"

[[files]]
file = "config/moderate-loading-screen.json5"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/moonlight-client.json"

[[files]]
file = "config/moonlight-common.json"

[[files]]
file = "config/moreiotas/client.json5"

[[files]]
file = "config/moreiotas/common.json5"

[[files]]
file = "config/moreiotas/server.json5"

[[files]]
file = "config/necronomicon.json5"

[[files]]
file = "config/neruina.json"

[[files]]
file = "config/notes.json"

[[files]]
file = "config/observable.json"

[[files]]
file = "config/ok-boomer.json5"

[[files]]
file = "config/oneironaut/client.json5"

[[files]]
file = "config/oneironaut/common.json5"

[[files]]
file = "config/oneironaut/server.json5"

[[files]]
file = "config/packages-client.cfg"

[[files]]
file = "config/packages-common.cfg"

[[files]]
file = "config/particle_core_config.toml"

[[files]]
file = "config/particle_core_disabled_optimizations.json"

[[files]]
file = "config/particlerain.json"

[[files]]
file = "config/patchouli.json5"

[[files]]
file = "config/paucal.json5"

[[files]]
file = "config/pehkui/config.json"

[[files]]
file = "config/puzzlesapi-iteminteractions-client.toml"

[[files]]
file = "config/puzzlesapi-iteminteractions-server.toml"

[[files]]
file = "config/puzzlesapi-slotcycling-client.toml"

[[files]]
file = "config/resourcepackoverrides.json"

[[files]]
file = "config/servercore/config.yml"

[[files]]
file = "config/servercore/optimizations.yml"

[[files]]
file = "config/servertick.toml"

[[files]]
file = "config/sodium-fingerprint.json"

[[files]]
file = "config/sodium-mixins.properties"

[[files]]
file = "config/sodium-options.json"

[[files]]
file = "config/spark/config.json"

[[files]]
file = "config/spark/tmp/about.txt"

[[files]]
file = "config/stackdeobf.json"

[[files]]
file = "config/styled-chat.json"

[[files]]
file = "config/styled-nicknames.json"

[[files]]
file = "config/supplementaries-client.json"

[[files]]
file = "config/supplementaries-common.json"

[[files]]
file = "config/surveyor.toml"

[[files]]
file = "config/toomanybinds.json5"

[[files]]
file = "config/tt20/block_entity_mask.json"

[[files]]
file = "config/tt20/config.json"

[[files]]
file = "config/unloaded-activity.json"

[[files]]
file = "config/villager-in-a-bucket.properties"

[[files]]
file = "config/vivecraft-client-config.json"

[[files]]
file = "config/vivecraft-server-config.toml"

[[files]]
file = "config/watut-client.toml"

[[files]]
file = "config/watut-common.toml"

[[files]]
file = "config/watut-item-arm-adjustments.json"

[[files]]
file = "config/watut-server.toml"

[[files]]
file = "config/xaerominimap-common.txt"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "config/xaerominimap_entities.json"

[[files]]
file = "config/xaeropatreon.txt"

[[files]]
file = "config/xaeroworldmap-common.txt"

[[files]]
file = "config/xaeroworldmap.txt"

[[files]]
file = "config/yacl.json5"

[[files]]
file = "config/yigd.json"

[[files]]
file = "mods/HexVR-1.6.0-85b3885.jar"

[[files]]
file = "mods/JadeAddons-1.20.1-Fabric-5.4.0.jar"

[[files]]
file = "mods/allium-0.4.0.jar"

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/antique-atlas-4.pw.toml"
metafile = true

[[files]]
file = "mods/anvil_heads.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/armourers-workshop.pw.toml"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/blaha-replushed.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/caduceus.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/chunkyborder.pw.toml"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/complexhex-fabric-1.20.1-0.1.6-beta-d433a18.jar"

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
metafile = true

[[files]]
file = "mods/create-estrogen.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-tweaks-0.1.1+1.20.1.jar"

[[files]]
file = "mods/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/cynosure.pw.toml"
metafile = true

[[files]]
file = "mods/deathlog.pw.toml"
metafile = true

[[files]]
file = "mods/defaulted-hotkeys.pw.toml"
metafile = true

[[files]]
file = "mods/distant-friends.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
metafile = true

[[files]]
file = "mods/dynmap.pw.toml"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
metafile = true

[[files]]
file = "mods/efhexs-1.0.0-20dbe0d.jar"

[[files]]
file = "mods/embeddedcomputer.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/ephemera-fabric-1.20.1-0.3.0.jar"

[[files]]
file = "mods/estrogen.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-ecosphere.pw.toml"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrication.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/fastback.pw.toml"
metafile = true

[[files]]
file = "mods/figura-0.1.5+1.20.1-fabric-mc-a5f5d5d.jar"

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/fsb-carpet-addon-0.1.1.jar"

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/gravity-api-fork.pw.toml"
metafile = true

[[files]]
file = "mods/helpfromhexxy-fabric-1.20.1-0.1.4.jar"

[[files]]
file = "mods/hex-machina.pw.toml"
metafile = true

[[files]]
file = "mods/hexal-fabric-1.20.1-0.3.1-821cc54.jar"

[[files]]
file = "mods/hexcassettes-2.0.0-b7d281b.jar"

[[files]]
file = "mods/hexcasting-fabric-1.20.1-0.11.3-7202ed7.jar"

[[files]]
file = "mods/hexcellular-1.1.0-04dcd44.jar"

[[files]]
file = "mods/hexchanting.pw.toml"
metafile = true

[[files]]
file = "mods/hexdebug.pw.toml"
metafile = true

[[files]]
file = "mods/hexical-2.0.0-e0d7ef9.jar"

[[files]]
file = "mods/hexodus.pw.toml"
metafile = true

[[files]]
file = "mods/hexpats.pw.toml"
metafile = true

[[files]]
file = "mods/hexportation.pw.toml"
metafile = true

[[files]]
file = "mods/hexpose.pw.toml"
metafile = true

[[files]]
file = "mods/hexstruction.pw.toml"
metafile = true

[[files]]
file = "mods/hextended-staves.pw.toml"
metafile = true

[[files]]
file = "mods/hexxyinthealps-fabric-0.1.0+1.20.1-SNAPSHOT.jar"

[[files]]
file = "mods/hierophantics.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
metafile = true

[[files]]
file = "mods/ioticblocks.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jline4mcdsrv.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
metafile = true

[[files]]
file = "mods/lesser-teleport.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/mediatransport.pw.toml"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
metafile = true

[[files]]
file = "mods/moderate-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/moreiotas.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/moves-the-mind.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/notes.pw.toml"
metafile = true

[[files]]
file = "mods/observable.pw.toml"
metafile = true

[[files]]
file = "mods/offlinecommands.pw.toml"
metafile = true

[[files]]
file = "mods/ok-boomer.pw.toml"
metafile = true

[[files]]
file = "mods/oneironaut-fabric-1.20.1-0.5.0.jar"

[[files]]
file = "mods/overevaluate-1.0.0-7ebb76e.jar"

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/packages.pw.toml"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/phlexiful.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/raknetify.pw.toml"
metafile = true

[[files]]
file = "mods/resource-pack-overrides.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/scryglass-1.0.0-6c096fb.jar"

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/slate-works.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/surveyor.pw.toml"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
metafile = true

[[files]]
file = "mods/too-many-binds.pw.toml"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/trinkhide-1.0.1+object-Object-9f4a62f.jar"

[[files]]
file = "mods/tt20.pw.toml"
metafile = true

[[files]]
file = "mods/unloaded-activity.pw.toml"
metafile = true

[[files]]
file = "mods/villager-in-a-bucket.pw.toml"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/xxl-packets.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/Hexxycraft/assets/complexhex/lang/en_us.json"

[[files]]
file = "resourcepacks/Hexxycraft/assets/hexcasting/patchouli_books/thehexbook/en_us/entries/greatwork/hexbox.json"

[[files]]
file = "resourcepacks/Hexxycraft/assets/hexcasting/patchouli_books/thehexbook/en_us/entries/greatwork/quenching_allays.json"

[[files]]
file = "resourcepacks/Hexxycraft/assets/hexcasting/patchouli_books/thehexbook/en_us/entries/patterns/spells/mage_blocks.json"

[[files]]
file = "resourcepacks/Hexxycraft/assets/hexcasting/patchouli_books/thehexbook/en_us/entries/patterns/spells/sample_block.json"

[[files]]
file = "resourcepacks/Hexxycraft/assets/hexical/lang/en_us.json"

[[files]]
file = "resourcepacks/Hexxycraft/assets/hexverb/lang/en_us.json"

[[files]]
file = "resourcepacks/Hexxycraft/assets/hexxyfour/lang/en_us.json"

[[files]]
file = "resourcepacks/Hexxycraft/pack.mcmeta"

[[files]]
file = "resourcepacks/toki-pona.zip"

[[files]]
file = "scripts/common/phials.zs"

[[files]]
file = "scripts/hexbox.zs"

[[files]]
file = "scripts/recipes/gift_sacks.zs"

[[files]]
file = "scripts/recipes/hex_changes.zs"

[[files]]
file = "scripts/recipes/merge_phials.zs"

[[files]]
file = "scripts/recipes/random_changes.zs"

[[files]]
file = "scripts/tags/everblacklist.zs"
