name = "Hexxy 4"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "151babffa23bff7e371b32d1fec12e595fb1d661007cda0e787e7750b4eaa45b"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
no-internal-hashes = true
