name = "Hexxy 4"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3354f71cadf4b02f3ada40723356da6f2fbd83a513266da5c2d40f12dbcd08e3"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
no-internal-hashes = true
